<script setup lang="ts">
import { computed } from 'vue'
import FilterPill from '@/components/molecules/FilterPill.vue'
import { sources, entityTypes, listTypes, statuses } from '@/config'

interface Filters {
  sources: string[]
  entityTypes: string[]
  listTypes: string[]
  statuses: string[]
}

const props = defineProps<{
  filters: Filters
  counts: {
    sources: Record<string, number>
    entityTypes: Record<string, number>
    listTypes: Record<string, number>
    statuses: Record<string, number>
  }
}>()

const emit = defineEmits<{
  'update:filters': [filters: Filters]
  'clear': []
}>()

const toggleSource = (code: string) => {
  const newSources = props.filters.sources.includes(code)
    ? props.filters.sources.filter(s => s !== code)
    : [...props.filters.sources, code]
  emit('update:filters', { ...props.filters, sources: newSources })
}

const toggleEntityType = (code: string) => {
  const newTypes = props.filters.entityTypes.includes(code)
    ? props.filters.entityTypes.filter(t => t !== code)
    : [...props.filters.entityTypes, code]
  emit('update:filters', { ...props.filters, entityTypes: newTypes })
}

const toggleListType = (code: string) => {
  const newListTypes = props.filters.listTypes.includes(code)
    ? props.filters.listTypes.filter(l => l !== code)
    : [...props.filters.listTypes, code]
  emit('update:filters', { ...props.filters, listTypes: newListTypes })
}

const toggleStatus = (code: string) => {
  const newStatuses = props.filters.statuses.includes(code)
    ? props.filters.statuses.filter(s => s !== code)
    : [...props.filters.statuses, code]
  emit('update:filters', { ...props.filters, statuses: newStatuses })
}

/**
 * Whether the published facet counts have arrived at all.
 *
 * Everything below distinguishes "this source publishes nothing" from "we do
 * not know yet", and the difference is not cosmetic: keyed on the counts alone,
 * every one of the fifteen pills rendered disabled and captioned "not yet
 * published" during prerender and until `facets/authorities.json` resolved —
 * and permanently if that request ever failed. A filter panel that tells a
 * reader the register publishes nothing is worse than one that says nothing.
 */
const countsLoaded = computed(() => Object.keys(props.counts.sources).length > 0)

/**
 * Whether a source can currently be filtered on.
 *
 * Derived from the counts this component is already given — which
 * `SearchPage` builds from the published `facets/authorities.json` — and
 * deliberately NOT from `publishesAggregate()` in `sourceCatalog.ts`, which is
 * the helper this looks like it should use.
 *
 * `SOURCES_WITHOUT_AGGREGATE` is a hand-maintained list, and on 2026-08-28 it
 * still named `un_vessels`, which had been publishing since 19 August: the
 * live facets endpoint returns 14 authorities including un_vessels at 59, and
 * excluding `ru`. Trusting the static list would therefore have greyed out a
 * source that works. The published facets cannot go stale in that direction,
 * because they are regenerated by the same run that publishes the data.
 */
const isFilterable = (code: string): boolean =>
  typeof props.counts.sources[code] === 'number' && props.counts.sources[code] > 0

/**
 * Whether to render a source as unavailable.
 *
 * Never before the counts exist, and never for a source the reader has already
 * selected: a selected-but-disabled pill loses both its pressed state and its
 * click handler, so the filter stays in the URL and in the result set with no
 * way left to remove it.
 */
const isUnavailable = (code: string): boolean =>
  countsLoaded.value &&
  !isFilterable(code) &&
  !props.filters.sources.includes(code)

/** How many sources a reader can actually narrow by, or 0 while unknown. */
const filterableSourceCount = computed(() =>
  countsLoaded.value ? sources.filter((s) => isFilterable(s.code)).length : 0,
)
</script>

<template>
  <div class="glass-card p-6">
    <div class="flex items-center justify-between mb-4">
      <h3 class="font-semibold text-light-text dark:text-dark-text">Filters</h3>
      <button
        @click="emit('clear')"
        class="text-sm text-brand-link hover:underline"
      >
        Clear all
      </button>
    </div>

    <div class="space-y-6">
      <div>
        <!--
          The heading counts what can actually be filtered, not what the
          catalogue names. `config.sources` lists 15 because `sourceCatalog.ts`
          keeps a code listed while its data repo is pending; the deploy
          publishes 14. This heading said "Sources (15)" directly beneath a
          page subtitle reading "Search across 14 data sources", and the
          fifteenth pill — Russia — rendered with no count and matched nothing.
        -->
        <h4 class="text-sm font-medium text-light-muted dark:text-dark-muted mb-3">
          Sources<span v-if="filterableSourceCount"> ({{ filterableSourceCount }})</span>
        </h4>
        <div class="flex flex-wrap gap-2">
          <FilterPill
            v-for="source in sources"
            :key="source.code"
            :label="source.name"
            :count="counts.sources[source.code]"
            :unavailable="isUnavailable(source.code)"
            :active="filters.sources.includes(source.code)"
            :color="source.color"
            @click="toggleSource(source.code)"
          />
        </div>
      </div>

      <div>
        <h4 class="text-sm font-medium text-light-muted dark:text-dark-muted mb-3">
          Entity Types ({{ entityTypes.length }})
        </h4>
        <div class="flex flex-wrap gap-2">
          <FilterPill
            v-for="type in entityTypes"
            :key="type.code"
            :label="type.icon + ' ' + type.name"
            :count="counts.entityTypes[type.code]"
            :active="filters.entityTypes.includes(type.code)"
            :color="type.color"
            @click="toggleEntityType(type.code)"
          />
        </div>
      </div>

      <div>
        <h4 class="text-sm font-medium text-light-muted dark:text-dark-muted mb-3">
          List Types ({{ listTypes.length }})
        </h4>
        <div class="flex flex-wrap gap-2">
          <FilterPill
            v-for="listType in listTypes"
            :key="listType.code"
            :label="listType.name"
            :count="counts.listTypes[listType.code]"
            :active="filters.listTypes.includes(listType.code)"
            @click="toggleListType(listType.code)"
          />
        </div>
      </div>

      <div>
        <h4 class="text-sm font-medium text-light-muted dark:text-dark-muted mb-3">
          Status ({{ statuses.length }})
        </h4>
        <div class="flex flex-wrap gap-2">
          <FilterPill
            v-for="status in statuses"
            :key="status.code"
            :label="status.name"
            :count="counts.statuses[status.code]"
            :active="filters.statuses.includes(status.code)"
            :color="status.color"
            @click="toggleStatus(status.code)"
          />
        </div>
      </div>
    </div>
  </div>
</template>
